### ISSUE TITLE
白天模式下显示问题

### ISSUE THREAD

**Issue by lifesign** [Anthonyeef/wuhan-virus-bitbar-plugin#1]
![image](https://user-images.githubusercontent.com/2189610/73259724-59f84780-4203-11ea-98fe-99b888eafa23.png)
如图，移上去会有文字显示

**Comment by Anthonyeef** [comment]
更新了，可以再试试看

**Comment by lifesign** [comment]
666 可以了~

**Comment by Anthonyeef** [comment]
搜了一下是 Bitbar 没做很好的 Darkmode 适配：https://github.com/matryer/bitbar/issues/532
我写死了 color = white，在白天模式下就看不出来文字了。

从 https://github.com/matryer/bitbar-plugins/blob/master/Time/shiftstats.30s.py#L44 偷学到了，可以先拿到当前的 darkmode，然后确定文字的颜色

不过看起来每次切换 Darkmode 都要重启一下 Bitbar，这个也没招了…
先暂时这样吧 🙏
