### ISSUE TITLE
submenu won't render properly in dark mode

### ISSUE THREAD

**Issue by mediter** [Anthonyeef/wuhan-virus-bitbar-plugin#11]
cities stats won't show, the length of submenu seems okay

<img width="529" alt="Screen Shot 2020-01-31 at 11 21 43 PM" src="https://user-images.githubusercontent.com/57368/73552536-61c61f00-4483-11ea-813d-2d6a84efe528.png">

**Comment by Anthonyeef** [comment]
https://github.com/Anthonyeef/wuhan-virus-bitbar-plugin/issues/1 

之前收到过反馈了，后面更新了一下；可以再看看

另外这个问题的根本原因是 Bitbar 没做好 macOS 的日夜间适配，我只能做一些 workaround 了
