### ISSUE TITLE
同步延时严重

### ISSUE THREAD

**Issue by hy4015** [Anthonyeef/wuhan-virus-bitbar-plugin#13]
丁香园的数据和同步过来的数据不一致，刷新了也没用。有延时

**Comment by Anthonyeef** [comment]
![image](https://user-images.githubusercontent.com/3444531/73623983-04e08980-467a-11ea-8c7e-f50b6aa8d86b.png)

是计算方法导致的；我的 `全国` 数据是将各省份的确诊人数相加，看丁香园的说明，他们的 `全国` 是有另外的来源

我调整一下，感谢反馈

**Comment by hy4015** [comment]
好像出问题了：





Best regards,

Thomas

**Comment by Anthonyeef** [comment]
我更新了一下，换成了新浪的接口

可以同步一下看看

**Comment by hy4015** [comment]
换成新浪的我的好像还是没有同步到正确的总人数：





Best regards,

Thomas

**Comment by Anthonyeef** [comment]
看一下 README；昨天更新了计算总人数的方法。可以再更新看看
